# Generated by Django 5.0 on 2023-12-25 13:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категории', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Опишите свою заявку ')),
                ('photo_file', models.ImageField(max_length=254, upload_to='image/', validators=[shop.models.Application.validate_image, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp'])])),
                ('status', models.CharField(choices=[('N', 'Новая'), ('P', 'Принято в работу'), ('C', 'Выполнено')], default='N', max_length=254, verbose_name='Статус')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('category', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
